
const bidsHistory = [
  {
    id: 1,
    item: "Gaming Laptop",
    highestBid: 950,
    yourBid: 850,
    status: "Active",
    date: "Today",
  },
  {
    id: 2,
    item: "Wireless Headphones",
    highestBid: 200,
    yourBid: 150,
    status: "Outbid",
    date: "2 days ago",
  },
  {
    id: 3,
    item: "Smart Watch",
    highestBid: 150,
    yourBid: 150,
    status: "Won",
    date: "5 days ago",
  },
  {
    id: 4,
    item: "iPhone 14 Pro",
    highestBid: 1100,
    yourBid: 1050,
    status: "Active",
    date: "Today",
  },
  {
    id: 5,
    item: "Mechanical Keyboard",
    highestBid: 180,
    yourBid: 160,
    status: "Outbid",
    date: "1 day ago",
  },
  {
    id: 6,
    item: "4K Monitor",
    highestBid: 420,
    yourBid: 420,
    status: "Won",
    date: "1 week ago",
  },
  {
    id: 7,
    item: "Bluetooth Speaker",
    highestBid: 120,
    yourBid: 95,
    status: "Outbid",
    date: "3 days ago",
  },
  {
    id: 8,
    item: "Gaming Mouse",
    highestBid: 90,
    yourBid: 90,
    status: "Won",
    date: "6 days ago",
  },
  {
    id: 9,
    item: "Tablet",
    highestBid: 360,
    yourBid: 330,
    status: "Active",
    date: "Today",
  },
  {
    id: 10,
    item: "Noise Cancelling Headphones",
    highestBid: 280,
    yourBid: 250,
    status: "Outbid",
    date: "4 days ago",
  },
];

export default bidsHistory;
