const myAuctionsMock = [
  {
    id: 1,
    item: "Gaming Laptop",
    category: "Electronics",
    currentBid: 850,
    status: "Active",
    endsIn: "03h 15m",
  },
  {
    id: 2,
    item: "Wireless Headphones",
    category: "Accessories",
    currentBid: 150,
    status: "Completed",
    endsIn: "Ended",
  },
  {
    id: 3,
    item: "iPhone 14 Pro",
    category: "Electronics",
    currentBid: 920,
    status: "Active",
    endsIn: "05h 40m",
  },
  {
    id: 4,
    item: "Mechanical Keyboard",
    category: "Accessories",
    currentBid: 120,
    status: "Active",
    endsIn: "01h 05m",
  },
  {
    id: 5,
    item: "4K Monitor",
    category: "Electronics",
    currentBid: 400,
    status: "Completed",
    endsIn: "Ended",
  },
  {
    id: 6,
    item: "Smart Watch",
    category: "Wearables",
    currentBid: 210,
    status: "Active",
    endsIn: "06h 30m",
  },
  {
    id: 7,
    item: "Bluetooth Speaker",
    category: "Audio",
    currentBid: 95,
    status: "Completed",
    endsIn: "Ended",
  },
  {
    id: 8,
    item: "Gaming Mouse",
    category: "Accessories",
    currentBid: 75,
    status: "Active",
    endsIn: "02h 50m",
  },
  {
    id: 9,
    item: "DSLR Camera",
    category: "Photography",
    currentBid: 680,
    status: "Active",
    endsIn: "09h 10m",
  },
  {
    id: 10,
    item: "Noise Cancelling Earbuds",
    category: "Audio",
    currentBid: 180,
    status: "Completed",
    endsIn: "Ended",
  },
];


export default myAuctionsMock;
