const myAuctionsMock = [
  {
    id: 1,
    item: "Gaming Laptop",
    title: "Gaming Laptop",
    description: "High performance gaming laptop, excellent condition.",
    category: "electronics",
    startingPrice: 700,
    bidIncrement: 25,
    duration: "7",
    currentBid: 850,
    status: "Active",
    endsIn: "03h 15m",
    sellerName: "TechWorld",
  },
  {
    id: 2,
    item: "Wireless Headphones",
    title: "Wireless Headphones",
    description: "Noise cancelling headphones, lightly used.",
    category: "accessories",
    startingPrice: 100,
    bidIncrement: 10,
    duration: "3",
    currentBid: 150,
    status: "Completed",
    endsIn: "Ended",
    sellerName: "TechWorld",
  },
  {
    id: 3,
    item: "iPhone 14 Pro",
    title: "iPhone 14 Pro",
    description: "128GB, unlocked, mint condition.",
    category: "electronics",
    startingPrice: 800,
    bidIncrement: 20,
    duration: "7",
    currentBid: 920,
    status: "Active",
    endsIn: "05h 40m",
    sellerName: "TechWorld",
  },
  {
    id: 4,
    item: "Mechanical Keyboard",
    title: "Mechanical Keyboard",
    description: "RGB mechanical keyboard with blue switches.",
    category: "accessories",
    startingPrice: 80,
    bidIncrement: 5,
    duration: "3",
    currentBid: 120,
    status: "Active",
    endsIn: "01h 05m",
    sellerName: "TechWorld",
  },
  {
    id: 5,
    item: "4K Monitor",
    title: "4K Monitor",
    description: "27-inch 4K UHD monitor, perfect for work and gaming.",
    category: "electronics",
    startingPrice: 300,
    bidIncrement: 15,
    duration: "7",
    currentBid: 400,
    status: "Completed",
    endsIn: "Ended",
    sellerName: "TechWorld",
  },
  {
    id: 6,
    item: "Smart Watch",
    title: "Smart Watch",
    description: "Fitness tracking smart watch with heart-rate monitor.",
    category: "wearables",
    startingPrice: 150,
    bidIncrement: 10,
    duration: "5",
    currentBid: 210,
    status: "Active",
    endsIn: "06h 30m",
    sellerName: "TechWorld",
  },
  {
    id: 7,
    item: "Bluetooth Speaker",
    title: "Bluetooth Speaker",
    description: "Portable speaker with deep bass and long battery life.",
    category: "audio",
    startingPrice: 60,
    bidIncrement: 5,
    duration: "3",
    currentBid: 95,
    status: "Completed",
    endsIn: "Ended",
    sellerName: "TechWorld",
  },
  {
    id: 8,
    item: "Gaming Mouse",
    title: "Gaming Mouse",
    description: "High DPI gaming mouse with programmable buttons.",
    category: "accessories",
    startingPrice: 50,
    bidIncrement: 5,
    duration: "3",
    currentBid: 75,
    status: "Active",
    endsIn: "02h 50m",
    sellerName: "TechWorld",
  },
  {
    id: 9,
    item: "DSLR Camera",
    title: "DSLR Camera",
    description: "Professional DSLR camera with 24MP sensor.",
    category: "photography",
    startingPrice: 600,
    bidIncrement: 20,
    duration: "7",
    currentBid: 680,
    status: "Active",
    endsIn: "09h 10m",
    sellerName: "TechWorld",
  },
  {
    id: 10,
    item: "Noise Cancelling Earbuds",
    description: "Wireless earbuds with active noise cancellation.",
    category: "audio",
    startingPrice: 140,
    bidIncrement: 10,
    duration: "3",
    currentBid: 180,
    status: "Completed",
    endsIn: "Ended",
    sellerName: "TechWorld",
  },
];

export default myAuctionsMock;
