
const usersMockData = [
  {
    id: 1,
    fullName: "Omar Abu Shmais",
    username: "omar_abu_shmais",
    email: "omar@gmail.com",
    status: "active",
    memberSince: "January 2025",
    role: "admin",
  },
  {
    id: 2,
    fullName: "Sarah Johnson",
    username: "sarah_johnson",
    email: "sarah.johnson@gmail.com",
    status: "active",
    memberSince: "March 2024",
    role: "user",
  },
  {
    id: 3,
    fullName: "Michael Brown",
    username: "michael_brown",
    email: "michael.brown@gmail.com",
    status: "inactive",
    memberSince: "July 2023",
    role: "moderator",
  },
  {
    id: 4,
    fullName: "Aisha Khaled",
    username: "aisha_khaled",
    email: "aisha.khaled@gmail.com",
    status: "active",
    memberSince: "November 2022",
    role: "user",
  },
  {
    id: 5,
    fullName: "David Miller",
    username: "david_miller",
    email: "david.miller@gmail.com",
    status: "inactive",
    memberSince: "February 2021",
    role: "user",
  },
  {
    id: 6,
    fullName: "Lina Haddad",
    username: "lina_haddad",
    email: "lina.haddad@gmail.com",
    status: "active",
    memberSince: "June 2023",
    role: "admin",
  },
  {
    id: 7,
    fullName: "James Wilson",
    username: "james_wilson",
    email: "james.wilson@gmail.com",
    status: "active",
    memberSince: "August 2020",
    role: "user",
  },
  {
    id: 8,
    fullName: "Fatima Noor",
    username: "fatima_noor",
    email: "fatima.noor@gmail.com",
    status: "inactive",
    memberSince: "December 2019",
    role: "moderator",
  },
  {
    id: 9,
    fullName: "Daniel Kim",
    username: "daniel_kim",
    email: "daniel.kim@gmail.com",
    status: "active",
    memberSince: "April 2022",
    role: "user",
  },
  {
    id: 10,
    fullName: "Emily Carter",
    username: "emily_carter",
    email: "emily.carter@gmail.com",
    status: "active",
    memberSince: "September 2021",
    role: "user",
  },
];
export default usersMockData;
